[versions]
spigot = "1.8.8-R0.1-SNAPSHOT"

[libraries]
spigot = { group = "org.spigotmc", name = "spigot", version.ref = "spigot" }
commandflow = { group = "me.fixeddev", name = "commandflow-bukkit", version = "0.5.2" }
inject = { group = "team.unnamed", name = "inject", version = "1.0.1" }
message-sourcetype-bukkit = { group = "me.yushust.message", name = "sourcetype-bukkit-yml", version = "7.0.0" }
annotations = { group= "org.jetbrains", name= "annotations", version= "23.0.0" }